apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot-app
spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80           # Internal service port
      targetPort: 8080   # Pod port (Spring Boot)
      nodePort: 30002    # External port on EC2 host
