apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot-app
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 80  # pod port
      nodePort: 30002   # allows browser access via EC2 public IP
